/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_nattysoft_eyethenticatenkosi_OpencvClass */
using namespace cv;
#ifndef _Included_com_nattysoft_eyethenticatenkosi_OpencvClass
#define _Included_com_nattysoft_eyethenticatenkosi_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nattysoft_eyethenticatenkosi_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_nattysoft_eyethenticatenkosi_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
